<?php
  if($this->getCollection()->count()>0):
?>
<ul class='bxslider' data-mage-init='{"SY_Slider/js/slider":<?php echo $this->getOptionsJson(); ?>}'>
<?php
  foreach($this->getCollection() as $item):
?>
<li class='bx-slide bx-slide-<?php echo $item->getData('id'); ?>'>
<?php
  if($item->getData('url')) echo '<a href=', $item->getData('url'), '>';
?>
<div class='bx-slide-img' style='background-image:url(<?php echo $this->getBaseUrl().'/'.ltrim($item->getData('image'), '/'); ?>)'></div>
<?php
  if($item->getData('url')) echo '</a>';
  
  if($item->getData('title') || $item->getData('caption')):
?>
<div class='bx-caption'>
<?php
  if($item->getData('title')) {
?>
<div class='bx-slide-title'>
<?php
  echo $item->getData('title');
?>
</div>
<?php
  }
  if($item->getData('caption')) {
?>
<div class='bx-slide-title'>
<?php
  echo $item->getData('caption');
?>
</div>
<?php
  }
?>
</div>
<?php
  endif;
?>
</li>
<?php
  endforeach;
  
  if (!empty(trim($this->getOption('css')))) {
?>
</ul>
<style type='text/css'>
<?php
    # inject styles typed-in CMS
    echo $this->getOption('css');
?>
</style>
<?php
    }
?>
<?php
  endif;
?>
